[2019-10-06 21:32:21,171] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:30: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

[2019-10-06 21:32:21,178] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:38: The name tf.train.exponential_decay is deprecated. Please use tf.compat.v1.train.exponential_decay instead.

[2019-10-06 21:32:21,184] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/venv/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
[2019-10-06 21:32:21,185] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:294: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
[2019-10-06 21:32:21,334] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x13a76f0d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x13a76f0d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
[2019-10-06 21:32:21,339] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/venv/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
[2019-10-06 21:32:21,351] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:118: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

[2019-10-06 21:32:21,351] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:121: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

[2019-10-06 21:32:21,351] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:121: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

[2019-10-06 21:32:21,465] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:129: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

[2019-10-06 21:32:21,465] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:133: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

[2019-10-06 21:32:21,489] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:136: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

[2019-10-06 21:32:21,507] INFO: fit on 9630 sample
[2019-10-06 21:32:24,266] INFO: [epoch-0, batch-0] -- Train Loss: 0.652727 NDCG: 0.327222 (0.407905) ERR: 0.211234  -- Valid Loss: 0.658822 NDCG: 0.377251 (0.443870) ERR: 0.213639 -- 2.758675 s
[2019-10-06 21:32:24,266] INFO: epoch: 1
[2019-10-06 21:32:24,380] INFO: epoch: 2
[2019-10-06 21:32:27,083] INFO: [epoch-2, batch-100] -- Train Loss: 0.627223 NDCG: 0.292490 (0.379591) ERR: 0.211234  -- Valid Loss: 0.642901 NDCG: 0.333902 (0.406719) ERR: 0.213639 -- 5.576243 s
[2019-10-06 21:32:27,127] INFO: epoch: 3
[2019-10-06 21:32:29,854] INFO: [epoch-3, batch-200] -- Train Loss: 0.601836 NDCG: 0.350812 (0.422713) ERR: 0.211234  -- Valid Loss: 0.615927 NDCG: 0.395027 (0.455326) ERR: 0.213639 -- 8.346636 s
[2019-10-06 21:32:29,877] INFO: epoch: 4
[2019-10-06 21:32:32,695] INFO: [epoch-4, batch-300] -- Train Loss: 0.588401 NDCG: 0.383230 (0.448310) ERR: 0.211234  -- Valid Loss: 0.602461 NDCG: 0.423085 (0.478453) ERR: 0.213639 -- 11.187690 s
[2019-10-06 21:32:32,698] INFO: epoch: 5
[2019-10-06 21:32:32,762] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/ltr/model.py:142: The name tf.train.write_graph is deprecated. Please use tf.io.write_graph instead.

[2019-10-06 21:32:32,831] INFO: /Users/neo1/PycharmProjects/vec4irltr/lr/weights/lr/model.checkpoint is not in all_model_checkpoint_paths. Manually adding it.
[2019-10-06 21:32:33,014] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x13ab9e4d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x13ab9e4d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
[2019-10-06 21:32:33,190] INFO: fit on 9630 sample
[2019-10-06 21:32:35,912] INFO: [epoch-0, batch-0] -- Train Loss: 0.652727 NDCG: 0.327222 (0.407905) ERR: 0.211234  -- Valid Loss: 0.658822 NDCG: 0.377251 (0.443870) ERR: 0.213639 -- 2.722092 s
[2019-10-06 21:32:35,912] INFO: epoch: 1
[2019-10-06 21:32:36,029] INFO: epoch: 2
[2019-10-06 21:32:38,785] INFO: [epoch-2, batch-100] -- Train Loss: 0.627223 NDCG: 0.292490 (0.379591) ERR: 0.211234  -- Valid Loss: 0.642901 NDCG: 0.333902 (0.406719) ERR: 0.213639 -- 5.594665 s
[2019-10-06 21:32:38,828] INFO: epoch: 3
[2019-10-06 21:32:41,596] INFO: [epoch-3, batch-200] -- Train Loss: 0.601836 NDCG: 0.350812 (0.422713) ERR: 0.211234  -- Valid Loss: 0.615927 NDCG: 0.395027 (0.455326) ERR: 0.213639 -- 8.406357 s
[2019-10-06 21:32:41,620] INFO: epoch: 4
[2019-10-06 21:32:44,453] INFO: [epoch-4, batch-300] -- Train Loss: 0.588401 NDCG: 0.383230 (0.448310) ERR: 0.211234  -- Valid Loss: 0.602461 NDCG: 0.423085 (0.478453) ERR: 0.213639 -- 11.262867 s
[2019-10-06 21:32:44,456] INFO: epoch: 5
[2019-10-06 21:32:44,643] INFO: /Users/neo1/PycharmProjects/vec4irltr/lr/weights/lr/model.checkpoint is not in all_model_checkpoint_paths. Manually adding it.
[2019-10-06 21:32:44,679] WARNING: From /Users/neo1/PycharmProjects/vec4irltr/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
[2019-10-06 21:32:44,680] INFO: Restoring parameters from /Users/neo1/PycharmProjects/vec4irltr/lr/weights/lr/model.checkpoint
